#!/usr/bin/env python3
"""Pack the .txt stories in this folder into main/hal/utils/stories_seeds.h.

At boot the firmware copies each one to the SD card (stackchan/historias/) if it is not there yet, so new
stories reach the card through a firmware flash (the Mac can't reach the robot's web page).
Keep file names ASCII (FAT long names are not UTF-8 here); the text itself can have accents.
    python3 assets_src/historias/build_seeds.py      # run from firmware/
"""
from pathlib import Path

HERE = Path(__file__).resolve().parent
OUT = HERE.parent.parent / "main/hal/utils/stories_seeds.h"

def c_string(text):
    out = []
    for line in text.replace("\r", "").split("\n"):
        esc = line.replace("\\", "\\\\").replace('"', '\\"')
        out.append(f'        "{esc}\\n"')
    return "\n".join(out)

files = sorted(p for p in HERE.glob("*.txt"))
for p in files:
    assert p.name.isascii(), f"Use an ASCII file name: {p.name}"
body = "\n".join(f'    {{"{p.name}",\n{c_string(p.read_text(encoding="utf-8").strip())}}},' for p in files)
OUT.write_text(f"""// Generated by assets_src/historias/build_seeds.py. Do not edit.
#pragma once

struct StorySeed {{
    const char* file;  // Name in stackchan/historias/ on the SD card
    const char* text;
}};

inline const StorySeed kStorySeeds[] = {{
{body}
}};
""", encoding="utf-8")
print(f"{len(files)} stories -> {OUT}")
